import { Activity, CheckCircle, Award } from "lucide-react";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
} from "recharts";
import { Card } from "@/components/ui/ui/card";
import type { PredictionQuality } from "@/types/activity";

interface PredictionQualityTabProps {
  predictionQuality: PredictionQuality;
}

export const PredictionQualityTab = ({
  predictionQuality,
}: PredictionQualityTabProps) => {
  const qualityData = [
    {
      name: "Untouched",
      value: predictionQuality.untouched,
      color: "hsl(var(--chart-2))",
    },
    {
      name: "Minor Edits",
      value: predictionQuality.minor_edits,
      color: "hsl(var(--chart-1))",
    },
    {
      name: "Major Edits",
      value: predictionQuality.major_edits,
      color: "hsl(var(--chart-3))",
    },
    {
      name: "Class Changes",
      value: predictionQuality.class_changes,
      color: "hsl(var(--chart-4))",
    },
    {
      name: "Rejected",
      value: predictionQuality.rejected,
      color: "hsl(var(--chart-5))",
    },
  ];

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="p-6">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium text-muted-foreground">
              Total Predictions
            </span>
            <Activity className="w-5 h-5 text-primary" />
          </div>
          <p className="text-3xl font-bold text-foreground">
            {predictionQuality.total_predictions.toLocaleString()}
          </p>
          <p className="text-sm text-muted-foreground mt-1">
            Generated by AI model
          </p>
        </Card>

        <div className="bg-gradient-to-br from-success-light to-success-light/50 rounded-lg shadow-sm border border-border p-6">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium text-success-foreground">
              Acceptance Rate
            </span>
            <CheckCircle className="w-5 h-5 text-success" />
          </div>
          <p className="text-3xl font-bold text-success">
            {predictionQuality.acceptance_rate}%
          </p>
          <p className="text-sm text-success-foreground/80 mt-1">
            High quality predictions
          </p>
        </div>

        <div className="bg-gradient-to-br from-primary-light to-primary-light/50 rounded-lg shadow-sm border border-border p-6">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium text-primary-foreground">
              Untouched
            </span>
            <Award className="w-5 h-5 text-primary" />
          </div>
          <p className="text-3xl font-bold text-primary">
            {predictionQuality.untouched_percentage}%
          </p>
          <p className="text-sm text-primary-foreground/80 mt-1">
            Perfect predictions
          </p>
        </div>
      </div>

      {/* Quality Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Pie Chart */}
        <Card className="p-6">
          <h3 className="text-lg font-semibold text-foreground mb-4">
            Prediction Quality Breakdown
          </h3>
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={qualityData}
                dataKey="value"
                nameKey="name"
                cx="50%"
                cy="50%"
                outerRadius={100}
                label={(entry) => `${entry.name}: ${entry.value}`}
              >
                {qualityData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        </Card>

        {/* Bar Chart */}
        <Card className="p-6">
          <h3 className="text-lg font-semibold text-foreground mb-4">
            Edit Type Distribution
          </h3>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={qualityData} layout="horizontal">
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis type="number" stroke="hsl(var(--muted-foreground))" />
              <YAxis
                dataKey="name"
                type="category"
                stroke="hsl(var(--muted-foreground))"
                width={100}
              />
              <Tooltip
                contentStyle={{
                  backgroundColor: "hsl(var(--card))",
                  border: "1px solid hsl(var(--border))",
                  borderRadius: "6px",
                }}
              />
              <Bar dataKey="value" radius={[0, 8, 8, 0]}>
                {qualityData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </Card>
      </div>

      {/* Detailed Metrics */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold text-foreground mb-6">
          Detailed Quality Metrics
        </h3>
        <div className="space-y-4">
          {qualityData.map((item) => {
            const percentage = (
              (item.value / predictionQuality.total_predictions) *
              100
            ).toFixed(1);
            return (
              <div key={item.name} className="flex items-center gap-4">
                <div className="w-32 text-sm font-medium text-foreground">
                  {item.name}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <div className="flex-1 bg-secondary rounded-full h-3">
                      <div
                        className="h-3 rounded-full transition-all"
                        style={{ width: `${percentage}%`, backgroundColor: item.color }}
                      />
                    </div>
                    <span className="text-sm font-medium text-muted-foreground w-16 text-right">
                      {percentage}%
                    </span>
                  </div>
                </div>
                <div className="w-24 text-right">
                  <span className="text-lg font-bold text-foreground">
                    {item.value.toLocaleString()}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </Card>

      {/* Insights */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-success-light border border-border rounded-lg p-6">
          <div className="flex items-start gap-3">
            <CheckCircle className="w-6 h-6 text-success flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-success-foreground mb-2">
                Model Performance
              </h4>
              <p className="text-sm text-success-foreground/80">
                {predictionQuality.untouched_percentage}% of predictions were
                accepted without any edits, indicating excellent model accuracy
                and user confidence.
              </p>
            </div>
          </div>
        </div>

        <div className="bg-primary-light border border-border rounded-lg p-6">
          <div className="flex items-start gap-3">
            <Activity className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-primary-foreground mb-2">
                Average Edit Magnitude
              </h4>
              <p className="text-sm text-primary-foreground/80">
                When predictions are edited, the average change is{" "}
                {(predictionQuality.avg_edit_magnitude * 100).toFixed(1)}%,
                suggesting most edits are minor refinements.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
